[DONT MERGE] Fix Callback Issue On Older Gtk
Dont Merge as we still get AttributeError: 'function' object has no
attribute 'button' despite the menus working. Need to Replace
event.button and event.time. Though the menu works without error on
newer Gtk versions so maybe a try is needed or something.

File "/home/doadin/Desktop/deluge/deluge/ui/gtkui/statusbar.py", line
431, in _on_connection_item_clicked
self.max_connections_global, show_notset=True, show_other=True)
File "/home/doadin/Desktop/deluge/deluge/ui/gtkui/common.py", line 78,
in build_menu_radio_list
menuitem = Gtk.RadioMenuItem(item_text, group)
TypeError: __init__() takes at most 2 arguments (3 given)